//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayTNCDriver.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int TransactionID { get; set; }
        public int JournalID { get; set; }
        public int TransactionTypeID { get; set; }
        public Nullable<int> ReversalID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public decimal Credit { get; set; }
        public decimal Debit { get; set; }
        public bool Cleared { get; set; }
        public Nullable<int> RelatedID { get; set; }
        public string RelatedTable { get; set; }
        public string Description { get; set; }
        public int PaymentTypeID { get; set; }
        public string PaymentNumber { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> BaseLocationID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string BatchNo { get; set; }
    
        public virtual JournalAccount JournalAccount { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
