//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayTNCDriver.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionType
    {
        public int TransactionTypeID { get; set; }
        public string TransactionType1 { get; set; }
        public bool SystemUse { get; set; }
        public bool Cashiers { get; set; }
        public bool Managers { get; set; }
        public decimal SetCredit { get; set; }
        public decimal SetDebit { get; set; }
        public decimal CreditLimit { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> DRUse { get; set; }
    }
}
