//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayTNCDriver.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAssociation
    {
        public int UsersAssociationID { get; set; }
        public string PortalUserID { get; set; }
        public Nullable<int> CarsUserID { get; set; }
        public int NumberAttemps { get; set; }
        public Nullable<System.DateTime> DateLocked { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual Driver Driver { get; set; }
    }
}
