//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayTNCDriver.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AchTransaction
    {
        public int TransactionID { get; set; }
        public int DriverID { get; set; }
        public string AccountNumber { get; set; }
        public string RoutingNumber { get; set; }
        public decimal Amount { get; set; }
        public short Type { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }
        public bool Processed { get; set; }
        public string LastError { get; set; }
        public Nullable<int> BatchNumber { get; set; }
        public Nullable<System.DateTime> DateProcessed { get; set; }
        public string ProcessedBy { get; set; }
    }
}
