//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayTNCDriver.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Driver()
        {
            this.UsersAssociations = new HashSet<UsersAssociation>();
        }
    
        public int DriverID { get; set; }
        public int DriverNumber { get; set; }
        public int ContactID { get; set; }
        public int DriverTypeID { get; set; }
        public string License { get; set; }
        public Nullable<System.DateTime> LicExpire { get; set; }
        public string SSN { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> TermDate { get; set; }
        public Nullable<System.DateTime> LastOut { get; set; }
        public int Status { get; set; }
        public int TempStatus { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public int SafeShifts { get; set; }
        public Nullable<int> BaseLocationID { get; set; }
        public Nullable<int> CurrentLocationID { get; set; }
        public int LeaseID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Alert { get; set; }
        public Nullable<bool> W9_Completed { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<int> CardUserID { get; set; }
        public string CardProxyNumber { get; set; }
        public string CardStatus { get; set; }
        public string CardNumber { get; set; }
        public string Gender { get; set; }
        public string AzureImagePath { get; set; }
        public Nullable<decimal> ACHAmountOnHold { get; set; }
        public Nullable<System.DateTime> ACHAmountOnHoldCreated { get; set; }
        public string ACHAmountOnHoldCreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersAssociation> UsersAssociations { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
